### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by effeci** [Snikii/Lenovo-ThinkPad-X240#1]
Cannot get audio working with these kexts in Mojave.... Managed to get it going with AppleAlc but it looks like it's working half volume. Any viable solution? Thanks

**Comment by Snikii** [comment]
The Audio patching structure has changed on macOS Mojave, therefore ALC3232.kext or as we know DummyHDA/Audio Injector patching isn't working, AppleALC is the way to go now.
Guides will be updated soon.
