### ISSUE TITLE
项目使用方法

### ISSUE THREAD

**Issue by ablewolf** [Snikii/Lenovo-Thinkpad-X240#3]
这个项目怎么用在自己的X240上面啊，全部粘贴进去好像不能生效一样，使用方法可以讲一下吗？或者发我邮箱也可以，谢谢ablewolf5210@gmail.com

**Comment by Sniki** [comment]
I have an old guide for High Sierra but things have changed since then and macOS Mojave and macOS Catalina guide are almost done, should be up tomorrow, i will link it there for you when it's ready

**Comment by Sniki** [comment]
I will reply to you when guide is ready and post link.
