### ISSUE TITLE
Catalina

### ISSUE THREAD

**Issue by simmy1232** [Snikii/Lenovo-Thinkpad-X240#4]
is this catalina updated/compatible?

**Comment by Sniki** [comment]
Yes it is, i have an old guide for High Sierra but things have changed since then and macOS Mojave and macOS Catalina guide are almost done, should be up tomorrow, i will link it there for you when it's ready

**Comment by simmy1232** [comment]
Hi, thanks! I used it to install Mojave on my x240 and directly updated to Catalina from the app store! Might need a help with continuity though but I'll just wait for the guide to be posted. Thank you again!

**Comment by Sniki** [comment]
Follow forums when guide is ready, you will see it on Catalina laptop guides forum on tmx86
Use forums for troubleshooting problems, will let you know when guide is ready.
Shouldn't be long but i keep working at multiple projects at once so that's why i takes longer.
