### ISSUE TITLE
Docking station support

### ISSUE THREAD

**Issue by Sniki** [Snikii/Lenovo-Thinkpad-X240#5]
I recently got a Docking station for Lenovo ThinkPad *40 series so i will add support for it across all ThinkPads model that i support.

To-Do list:
- [x] USB ports
- [x] Ethernet
- [x] DisplayPort
- [x] VGA port
- [ ] DVI port
- [x] Audio Jack
- [ ] Fix DisplayPort Audio when using the Dock
- [ ] Fix Kernel Panic on Sleep, Restart or ShutDown when VGA/DVI/DisplayPort connected

**Comment by simmy1232** [comment]
Hi @Sniki ! That's good to know! Also, I know you're on open core right now but the new **Clover r5100** seems to have change some things on dsdt patching that left most x240s that are using **Clover** can't go to sleep when closing the lid of the laptop. I hope you can address the issue.

**Comment by Sniki** [comment]
I only got 1 person on tmx86 that reported this issue which is probably you ?,
Anyway im busy with other projects for now, will take a look on it when i get some time.
Use forums for that.

**Comment by kasik96** [comment]
Thank you <3. Biggest problem with dock is that Kernel Panic, i have it all the time.

**Comment by Sniki** [comment]
> Thank you <3. Biggest problem with dock is that Kernel Panic, i have it all the time.

@kasik96 that's a remaining issue that won't have a fix at least for now, i described the problem to Acidanthera.
They just said that seems to be a problem within Apple drivers.
Anyway maybe we need to raise more attention towards this problem by creating a thread or something somewhere and maybe someone will come up with a solution.
I wrote them here: https://github.com/acidanthera/bugtracker/issues/619

Tried all the current solutions but couldn't figure one out till now.

**Comment by Sniki** [comment]
Closing, no current working solution or interest of development into this problem until further development.

**Comment by masterbachelormaster** [comment]
Hey @Sniki ! Could you let me know how you made the DisplayPort on your dock work? I have a T450s and was able to successfully map the USBPorts, but just have no clue how to activate DisplayPort. You were the only person I could find that worked his ass off on this dock. Would really really  appreciate ur insight. Peace!

**Comment by swatchie-1** [comment]
Hello @rogerters and @Sniki yeah i'm having issues with using the Dock's display ports too. It panics everytime we sleep or reboot. Other stuffs work fine. Current workaround is to use the laptop's built in mini display port. Using T440P with 40A2 dock by the way.

**Comment by masterbachelormaster** [comment]
@swatchie-1 that's what I've done now as well... just bought a mini DP to DVI adapter. 

How did u even manage to make the DP and DVI port work in the first place?

**Comment by swatchie-1** [comment]
@rogerters yeah. am using T440P though. 
Am using the USBPorts.kext version 2.2.0 in this repo.
