### ISSUE TITLE
Working Intel Wifi

### ISSUE THREAD

**Issue by ghost** [Snikii/Lenovo-Thinkpad-X240#6]
Hi Sniki! I am currently using your x240 config in this github repo and it's working great! I have been using my hack for 4 months now without crashes and errors. 

For now you might want to check this github issue regarding with intel wifi. A user linked an Intel wifi kext (scroll down the github issue to download the latest) and somehow users say that it is working and  they have connected with the internet. They also say that it is best to use the kext with 7xxx rather than 8xxx/9xxx. So you might want to try and test it with x240's own Intel wifi card.

https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/330

**Comment by Sniki** [comment]
> Hi Sniki! I am currently using your x240 config in this github repo and it's working great! I have been using my hack for 4 months now without crashes and errors.
> 
> For now you might want to check this github issue regarding with intel wifi. A user linked an Intel wifi kext (scroll down the github issue to download the latest) and somehow users say that it is working and they have connected with the internet. They also say that it is best to use the kext with 7xxx rather than 8xxx/9xxx. So you might want to try and test it with x240's own Intel wifi card.
> 
> [daliansky/XiaoMi-Pro-Hackintosh#330](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/330)

Thanks for providing this !
