### ISSUE TITLE
Ready to use?

### ISSUE THREAD

**Issue by imperaughier** [Snikii/Lenovo-Thinkpad-X240#7]
Hi! Is this config ready to use for install or will you add more to it? Thanks for the hard work :)

**Comment by Sniki** [comment]
> Hi! Is this config ready to use for install or will you add more to it? Thanks for the hard work :)

Yes, grab the config and the SSDTs on ACPI folder.
Now they are separated instead of SSDT-X240.aml but it's for better.

Will also publish the guides soon.
