### ISSUE TITLE
Opencore efi ?

### ISSUE THREAD

**Issue by guaychou** [Snikii/Lenovo-Thinkpad-X240#8]
First of all, i apologize to open this issue, do you have thinkpad x240 opencore efi folder in this repo ? Would you like to share with us ?

**Comment by mrwiwi** [comment]
Yeah author, please give of some details :)

**Comment by alexhaydock** [comment]
He is planning to post it soon: https://www.tonymacx86.com/threads/guide-lenovo-thinkpad-x240.245580/post-2092198

**Comment by mrwiwi** [comment]
Thanks ! But for the moment, someone who is trying to boot an install disk, is it clover or oc version ?

**Comment by alexhaydock** [comment]
Well @Sniki's reply in Sniki/Lenovo-Thinkpad-T440P#6 suggests they are working on an OpenCore EFI soon, but I don't think this is a valid OpenCore config judging by the sanity checker at https://opencore.slowgeek.com, which shows it missing a bunch of sections. Possibly I am missing something though. Seems like we should wait for Sniki's guide.

**Comment by guaychou** [comment]
I tried the dsdt patched, it worked in clover

The new config.plist use smbios macbookprp11,1 instead of macbook air 6,2 from the forum

**Comment by mrwiwi** [comment]
I can't have it to boot an installation media... Is there anything I missed ? I'm far from new to hackintosh but I tried everything from Windows and Linux, clover or opencore... Never got pasted clover init (got the infinite apple with no sign of life)

**Comment by mrwiwi** [comment]
> I tried the dsdt patched, it worked in clover
> 
> The new config.plist use smbios macbookprp11,1 instead of macbook air 6,2 from the forum

No kexts needed (except the SMC stuff) ?
Could you please share an efi folder ?

**Comment by Sniki** [comment]
I will update files soon and provide Monthly OpenCore EFI builds so all you have to do is just to replace EFI and you are done (aside some minor personal changes like):
- Your SMBIOS values (those are unique for each individual to have working iMessage etc)
- Specific patches to your Wireless Card (DW1820A, DW1560, DW1830, etc).

The rest is configured so you won't need to worry about it.

**Comment by mrwiwi** [comment]
> I will update files soon and provide Monthly OpenCore EFI builds so all you have to do is just to replace EFI and you are done (aside some minor personal changes like):
> 
> * Your SMBIOS values (those are unique for each individual to have working iMessage etc)
> * Specific patches to your Wireless Card (DW1820A, DW1560, DW1830, etc).
> 
> The rest is configured so you won't need to worry about it.

Will it be suitable to make an install disk too ? I've never got it to boot on the x240, clover or opencore, but haven't tried hard enough I guess ;)

**Comment by swatchie-1** [comment]
Hi @Sniki can we try your opencore for T440P soon?

**Comment by Sniki** [comment]
Lenovo ThinkPad X240 OpenCore guide is up:
https://www.tonymacx86.com/threads/guide-lenovo-thinkpad-x240-opencore-0-5-9.299284/

All the latest and greatest improvements (that are not uploaded here on github yet) are include like (ACPI, Kexts, Drivers, Patches, etc)

**Comment by mrwiwi** [comment]
Thx @Sniki for all that work, i tried to boot to install, and for the 1st time i get to UI, but image is totally distorted, except for the mouse, menus are respinsive but unreadables, you got any idea ?

New to clver, and pretty old to hackintish here (started with tiger, stopped back to snow leopard :)).

Thanks in advance !

**Comment by mrwiwi** [comment]
> Thx @Sniki for all that work, i tried to boot to install, and for the 1st time i get to UI, but image is totally distorted, except for the mouse, menus are respinsive but unreadables, you got any idea ?
> 
> New to clver, and pretty old to hackintish here (started with tiger, stopped back to snow leopard :)).
> 
> Thanks in advance !

Ok, just close the lid and reopen, it's good ;)

**Comment by Sniki** [comment]
> > Thx @Sniki for all that work, i tried to boot to install, and for the 1st time i get to UI, but image is totally distorted, except for the mouse, menus are respinsive but unreadables, you got any idea ?
> > New to clver, and pretty old to hackintish here (started with tiger, stopped back to snow leopard :)).
> > Thanks in advance !
> 
> Ok, just close the lid and reopen, it's good ;)

Just enable CSM in bios and the problem is gone.

**Comment by guaychou** [comment]
Hey sniki, sorry to open it again, can the opencore config in your post boot the Mojave ?

Because I got stuck at apple logo

I already disable 4 kext wifi like your mention in post, but still didn't work

**Comment by guaychou** [comment]
okay @Sniki , i don't know what to do, but your config didn't work in mojave, so i decide to upgrade to latest catalina 10.15.6 and get worked with. Thank you
